// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOtQhYVXeMXWaggUcvyH9JgfW_N8QJOU',
    appId: '1:351554012505:web:bd62eab13b285b236a7848',
    messagingSenderId: '351554012505',
    projectId: 'tnpkiit-66650',
    authDomain: 'tnpkiit-66650.firebaseapp.com',
    storageBucket: 'tnpkiit-66650.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9Y8j55z0CiN5bnbjbUy75z3M7qE96DE',
    appId: '1:351554012505:android:ac6071dea2ff1ec36a7848',
    messagingSenderId: '351554012505',
    projectId: 'tnpkiit-66650',
    storageBucket: 'tnpkiit-66650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-2sRgsaoidftiK44eXAPIlOOthqHf18',
    appId: '1:351554012505:ios:a4a03163e0da20236a7848',
    messagingSenderId: '351554012505',
    projectId: 'tnpkiit-66650',
    storageBucket: 'tnpkiit-66650.appspot.com',
    androidClientId: '351554012505-drjdpb91anl0fame3h1lv90g3mpqn5tj.apps.googleusercontent.com',
    iosClientId: '351554012505-mprqn50mj0dabeo8eifv2qlv1l5ohcco.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiitcorridor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-2sRgsaoidftiK44eXAPIlOOthqHf18',
    appId: '1:351554012505:ios:e0916d20ca14a9a76a7848',
    messagingSenderId: '351554012505',
    projectId: 'tnpkiit-66650',
    storageBucket: 'tnpkiit-66650.appspot.com',
    androidClientId: '351554012505-drjdpb91anl0fame3h1lv90g3mpqn5tj.apps.googleusercontent.com',
    iosClientId: '351554012505-tpueetoplnfg48us3ipdbebkgjk5s50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiitcorridor.RunnerTests',
  );
}
